### ISSUE TITLE
리소스 관리 방식 조사

### ISSUE THREAD

**Issue by Cytochrome8942** [dark-gammaru/Smart_Factory#10]
# 이슈 목표
mesh 등을 인스턴스가 저장하는 것은 지양하라고 함.
가공물 및 생산물 Actor 생성, mesh 변경에 사용할 방식 조사
https://docs.unrealengine.com/4.26/ko/Resources/SampleGames/ARPG/BalancingBlueprintAndCPP/

# 요구 사항
1. Asset manager, Game data 에셋, 블루프린트 등 이용.
2. String으로 path를 하드코딩하는 방식은 지양.
3. 가공물, 생산물, mesh의 종류가 많음, 방식 채택시 고려.

**Comment by NaTure77** [comment]
Data Table의 행이름으로 순회 돌며 요소 가져오는 방법(블루 프린트)
1. Data Table 타입의 변수 생성
2. 생성한 변수에 원하는 데이터를 기본값으로 지정.
3. Get Data Table Row Names를 이용하여 변수의 Row Names를 가져옴
4. For Each Loop로 Row Names를 순회.
5. Row Name마다 '데이터 테이블 행 가져오기' 수행
![image](https://user-images.githubusercontent.com/18459135/162561644-b9b89e83-9c09-4519-9095-38c6796c29c8.png)

**Comment by Cytochrome8942** [comment]
DataTableRow.cpp의 struct를 사용하여 Commodity Table 생성 완료
