### ISSUE TITLE
잠자기

### ISSUE THREAD

**Issue by Cytochrome8942** [dark-gammaru/Smart_Factory#13]
# 이슈 목표
침대랑 상호작용 시 즉시 잠들고 다음날 6시가 됨.

# 요구 사항
PlayerInteraction 리팩터링 완료 후 진행

**Comment by Cytochrome8942** [comment]
눈꺼풀을 이미 있는 widget과 떼는 작업 필요
한 번 누르면 반쯤 잠들고, 두 번 누를 때 잠드는 방식

**Comment by NaTure77** [comment]
완료
