### ISSUE TITLE
인간 정보 제작 및 임의 생성

### ISSUE THREAD

**Issue by Cytochrome8942** [dark-gammaru/Smart_Factory#14]
# 이슈 목표
플레이어 / NPC에 쓰일 인간의 정보 저장 및 pool에서 랜덤 선택 (DataTable 등 이용)

# 요구 사항
1.
- 다국적의 랜덤 이름 (남자/여자 이름 구분)
- 텍스트 정보 : 성별, 혈액형, 생월,일 (생년은 없음), 
인종 http://indosarang.com/indonesia/qna/7436 의 5대 인종 사용 : 피부색과 관련
프사 : 혹시라도 가능하다면 NPC 사진이 남아있게 돼서 몰입감이 증가할 듯.
다만 잠깐 검색해본 결과 유료인 경우가 많고, 무료더라도 인간 정보의 조합이 불가능해지므로 기본적으로 불가능이라고 전제.

2. 게임이 시작할 때 8명 분 겹치지 않게 랜덤 생성.

~~3. 언리얼 Metahuman 사용, 플레이어 정보에 해당하는 메타휴먼 선택.
동적으로 생성하는 방법은 없고, 플레이어 전용 N개의 인간을 미리 만들어 놓고 선택하는 방식인 듯.
언리얼5가 되면서 바뀌었을 수 있으므로 확인할 필요 있음.~~
3. 흑인 / 황인 / 백인 - 남자 / 여자 6개의 모델 준비 및 사용. 선택사항.

# 비고
- [x] 정보 테이블 제작
- [x] 랜덤 정보 생성

**Comment by unagi11** [comment]
가짜 얼굴 생성 : https://generated.photos/ (상업적 이용하려면 구독해야함. 15장에 2만원)
가짜 얼굴 생성2 : https://thispersondoesnotexist.com/
가짜 정보 생성 : https://www.daleseo.com/python-faker/

**Comment by unagi11** [comment]
다음의 정보를 조합하여 가상의 인물을 제작한다.

> ## Image
> 이미지 풀에서 랜덤하게 결정한다. 이미 사용한 이미지는 사용할 수 없다. (중복 불가)

> ## Race
> 이미지와 알맞은 인종을 사용한다.
> 1. Caucasoid
> 2. Mongoloid
> 3. Capoid
> 4. Congoid
> 5. Australoid

> ## Sex
> 이미지와 알맞은 성별을 사용한다.
> 1. male
> 2. female

> ## Blood Type
> 랜덤한 혈액형을 사용한다.
> 1. Rh+A
> 2. Rh-A
> 3. Rh+B
> 4. Rh-B
> 5. Rh+O
> 6. Rh-O
> 7. Rh+AB
> 8. Rh-AB

> ## Name
> 성별에 알맞는 라틴 이름을 배정받는다.

**Comment by unagi11** [comment]
## 현재 리소스
Image
- Caucasoid Female (6)
- Caucasoid Male (9)
- Mongoloid Female (9)
- Mongoloid Male (8)
- Black Male (12)

Name
- Male Name (1000)
- Female Name (1000)

https://drive.google.com/drive/folders/1-n65_4hWIcWW-cwth2L3Sz2U0v6PQ6Oq?usp=sharing

**Comment by Cytochrome8942** [comment]
구현 완료
