### ISSUE TITLE
상호작용 HUD

### ISSUE THREAD

**Issue by Cytochrome8942** [dark-gammaru/Smart_Factory#2]
# 이슈 목표
거래소, 인큐베이터, 채굴기에서 사용할 상호작용 HUD,
모든 상호작용 HUD에서 공통적으로 사용할 Base 클래스의 제작.

# 요구 사항
1. 상호작용 시 카메라로 패널 확대
2. 상호작용 시 player controller의 마우스 이동 비활성화. Input Bind의 일시적 비활성화 등 방법 찾아볼 것.
3. 마우스로 UI 버튼 조작

# 비고
제작한 base 클래스를 거래소, 인큐베이터, 채굴기에서 상속받아 사용할 것임.

**Comment by unagi11** [comment]
자료 조사
- [UMG 시작에서 최적화까지](https://youtu.be/6SaKxTv1GII)
- [블루프린트 강좌](https://youtube.com/playlist?list=PLi6SIeAlP8AVvHzAVv5ZGApb4dVva40dy)
- [Space-Game 3D UMD](https://randomcreations.wtf/b/space-game/)
- [WTF Is? Widget Interaction Component in Unreal Engine 4](https://www.youtube.com/watch?v=_1zWWabWof0)

**Comment by unagi11** [comment]
패널 레퍼런스 그림

![image](https://user-images.githubusercontent.com/18459532/163668081-03842450-f21f-4f92-a1b1-33f0f7d96cad.png)
![image](https://user-images.githubusercontent.com/18459532/163668091-ddae828a-4c64-4a4d-969a-80391445d7d4.png)
![image](https://user-images.githubusercontent.com/18459532/163667973-bb3e02b3-35bf-4001-9d81-9005dbc9f5d9.png)
